import type { Metadata } from 'next'
import './globals.css'
import { Header } from '../components/layout/header'
import { Toaster } from '../components/ui/sonner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body>
        <div className="flex flex-col h-screen">
          <Header />
          <main className="flex-1 p-4 sm:p-6 lg:p-8 mt-[64px]">{children}</main>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
