import type { Metadata } from 'next'
import './globals.css'
import { AUTH_TOKEN_KEY } from '@/constants/auth-token-key'
import { clsx } from 'clsx'
import { cookies } from 'next/headers'
import { Header } from '../components/layout/header'
import { Sidebar } from '../components/layout/sidebar'
import { Toaster } from '../components/ui/sonner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const token = cookieStore.get(AUTH_TOKEN_KEY)
  const isLoggedIn = !!token

  return (
    <html lang="ja">
      <body>
        <div className="flex flex-col h-screen">
          <Header />
          <div className={clsx('flex flex-1', 'h-[calc(100vh-64px)]')}>
            <Sidebar />
            <main className={clsx('flex-1 mt-16', isLoggedIn && 'ml-64')}>
              {children}
            </main>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
